apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: y7eybe4wm-nodejs 
  janus-idp.io/tekton: y7eybe4wm-nodejs
  backstage.io/kubernetes-id: y7eybe4wm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y7eybe4wm-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  